### PR TITLE
Logging update

### PR DESCRIPTION
**Pull request by cordeezy2**

### CODE REVIEW

**Comment by ghost** [comment]
Is there a way to default to no file logging?  Maybe  make a `LOG_TO_FILE` variable or something?

**Comment by cordeezy2** [comment]
The default logger is configured to create a logfile if one doesn't exist. 
We can change the default logger to only log to the console. 
If that is going to be the case, should INFO still be the default level ? Or should DEBUG be the default level?

**Comment by ghost** [comment]
@cordeezy2 Ok defaulted to only console logging only.

Can you add examples to examples dir on how to:
- Change logging level
- Change to JSON
- Enable File or Rotating File

**Comment by cordeezy2** [comment]
ready for review @justinjeffery-ipf

**Comment by ghost** [comment]
I am very confused... If I install ipfabric from pip how do I change the logging methods?  The examples say to copy files over logg.py but this should never be done when doing pip install.  Examples should be like:

```
import ipfabric
import logging
logging.getLogger('python-ipfabric').setLevel(logging.DEBUG)
logging.getLogger('python-ipfabric').addHandler(logging.NullHandler())
```

**Comment by cordeezy2** [comment]
users of this package project shouldnt be touching logg.py in general.
If you want to explicitly change the logging (or add some custom logging to send logs to file) then you would need to override the settings in logg.py.
Users of this package should incorporate a different logger for logging in their applications, users should not be setting the log level via `logging.getLogger('python-ipfabric').setLevel(logging.DEBUG)`. 
the logger 'python-ipfabric' should be only used for logging thoughout this project. 
logg.py houses the logging framework for this project, it is not meant to be a logging system for users of the project 


however when the CLI gets introduced, there will be options from the cli that can set the log levels for this entire project, that is the whole purpose of having control of logging via logg.py.

edit:
if a user wanted debug loggs coming from IPFabric they would simply add a root logger to their application and set the root logger to debug.

**Pull request merged**
